---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/ehra1/ehra1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/193884/master/file/figures/ehra1/ehra1.png"
